---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: notify
  image: plugins/matrix:1
  pull: always
  settings:
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
  when:
    event:
    - push
    - tag
    status:
    - failure

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**
